#制定编译规则１
main:main.o cal.o arr.o
	gcc -o main main.o cal.o arr.o
#制定编译规则２
main.o:main.c
	gcc -c -o main.o main.c
#制定编译规则３
cal.o:cal.c
	gcc -c -o cal.o cal.c
#制定编译规则４
arr.o:arr.c
	gcc -c -o arr.o arr.c
